### ISSUE TITLE
How to  Stabilize Latency - Best Practices and Guidelines 

### ISSUE THREAD

**Issue by naveedaziz** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#95] opened 2020-09-07 03:18 UTC
Hi, I am getting 10s+ latency with some devices and on different internet devices. Please guide what should i do to limits the latency and how to control latency across all or major devices/ISPs.
I have implemented the code as per guidelines and now i want optimization in the call/conference call.

**Comment by naveedaziz** [comment] 2020-09-08 01:57
How can we use HLS and kinesis webrtc

**Comment by lherman-cs** [comment] 2020-09-09 16:34
@naveedaziz Would you mind to describe your use cases more? I'm not sure why you want to use HLS with WebRTC.

**Comment by naveedaziz** [comment] 2020-09-14 02:42
Dear, i am trying to optimze connection but from [**VIEWER] Generated ICE candidate** to **[VIEWER] All ICE candidates have been generated** takes almost 40 to 50 seconds. Can we reduce that time ??

**Comment by lherman-cs** [comment] 2020-09-14 20:25
@naveedaziz did you enable trickle ICE? What browser did you use? 

If you disabled trickle ICE and used Chrome, this is a well known issue. Please take a look here for more details, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/issues/53#issuecomment-635416351.

**Comment by naveedaziz** [comment] 2020-09-15 05:51
Yes, sorry i missed that, Now its quick. 
Also i have to ask i have created conference call solution over kinesis webrtc. Now with one to one call it works good, but once 3rd person join it misses video randomly, means some times shows to all 3 but some times one of the person video is not showing to other.
I am using mesh architecture. 
Like 
Person 1 is master and Person 2 can see his video as viewer
Person 1 is master and Person 3 can see his video as viewer
Person 2 is master and Person 1 is viewing as viewer
Person 2 is master and Person 3 is viewing as viewer
Person 3 is master and Person 1 can see as viewer
Person 3 is master and Person 2 can see as viewer

Is the structure is right, and also why it's missing the stream some times.
I can share logs if required.

**Comment by naveedaziz** [comment] 2020-09-16 01:18
I think i have resolved the issue and it's working fine now. 💯 
Now i have 2 questions.
1) How i can record the sessions of conference call.
2) How to mute call and video stop stream using kinesis webrtc.

Might be thats last questions else all working superb

**Comment by MushMal** [comment] 2020-09-16 02:18
The first question is very involved one. You might choose a participant in your mesh to do the composition and recording with following producing into KVS stream for example. I would recommend working with your AWS account management team on the solution architecture.

The second one I assume you refer to is webrtc. I would recommend cutting a separate issue that people from the community can address

**Comment by naveedaziz** [comment] 2020-09-17 19:02
Dear, i cant understand **"The first question is very involved one. You might choose a participant in your mesh to do the composition and recording with following producing into KVS stream for example. I would recommend working with your AWS account management team on the solution architecture."**

**Comment by MushMal** [comment] 2020-09-17 19:42
What I meant by this is that "recording" can be interpreted in a number of ways when there are multiple participants. You could, for example, persist all of the participants separately. This won't be as useful for audio for example where you might want to composite it first and persist a single stream. At any rate, these are solution architecture items that we don't support out-of-the-box

**Comment by naveedaziz** [comment] 2020-09-20 06:21
Dear, actually the problem i am getting is when i connect user more than 3 in the conference call. It start behaving strange and random disconnects happens with multiple users. Can you help in that.

**Comment by chai2** [comment] 2020-10-03 09:51
+1 - using the example, I am not able to connect a third user to the session. While 1-1 works fine, I just can't get a third user to view the "master" stream. Any insights @lherman-cs ? thank you.

**Comment by lherman-cs** [comment] 2020-10-05 16:43
@naveedaziz @chai2 I'm not sure where the problem is without having the logs.

Since the original question has been answered, I've created a new issue to track this and will closed this. Here's the new issue link, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/issues/99.

**Comment by lherman-cs** [comment] 2020-10-05 16:43
@naveedaziz @chai2 please provide the logs for the issue in the new link.

**Closed by lherman-cs** 2020-10-05 16:43 UTC
