### ISSUE TITLE
Unexpected SDP offer from AWS_DEFAULT_SINGLE_MASTER upon sending SDP offer

### ISSUE THREAD

**Issue by life-efficient** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#25] opened 2020-04-09 12:45 UTC
Hi guys!

Firstly, I've made this as simple as possible to reproduce, and I'm sure one of you can crack it.

Full issue described and test UI implemented.

Check out this repo: https://github.com/life-efficient/rtcTests

Please let me know how I can help!

**Comment by MixMasterMitch** [comment] 2020-04-09 22:02
I have run your repo + test scenario and confirmed the behavior you describe. There is a service bug that is resulting in the "AWS_DEFAULT_SINGLE_MASTER" message you getting back, but will be fixed soon. What will happen is that the offer will be just be dropped. This is because masters are not allowed to send SDP Offers. See [SendSdpOffer docs](https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-websocket-apis3.html). But the KVS WebRTC Signaling Service now supports the use of correlation ids which enables the service to send error messages in response to invalid inputs (such as in this case), but the JS SDK does not support those yet.

**Comment by life-efficient** [comment] 2020-04-10 10:52
How can a Master do anything that requires negotiation then? Such as adding a screenshare to a peer connection. It will need to send an SDP offer to the receiver, right?

**Comment by MixMasterMitch** [comment] 2020-04-13 18:04
Per our other conversation, workaround right now is to send the SDP offer from the master via data channels.

The service team is working on adding support for Masters to send SDP offers, and Viewers to send SDP answers. No ETA.

**Closed by MixMasterMitch** 2020-04-13 18:04 UTC
