### ISSUE TITLE
Reconnection issues only with Firefox

### ISSUE THREAD

**Issue by ulayera** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#65] opened 2020-06-16 19:17 UTC
I'm working on a 3 way call with Kinesis on a Mesh topology on Web using Angular. I pretty much used the same code in the Test Page (master.js - viewer.js) with these variations: useIceTrickle: yes, natTraversalDisabled: no, forceTURN: no and the reconnection process repeated (same logic but repeating the SDPOffer on VIEWER when remote MASTER disconnects).

The issue: Reconnection works fine on Chrome, but it is not working on Firefox. First Firefox connection succeeds if Master connects first and then Viewer, but if Master reloads the page connection can't be achieved: sdpOffer gets sent, we get an sdpAnswer but iceConnection never happens, we get 'WebRTC: ICE failed, see about:webrtc for more details' (which seems to happen even if we don't try to reconnect at all). Looking at about:webrtc we get ICE State cancelled on every iceMessage.

Things we have tried with no luck: We tried sending SdpOffer with "iceRestart: true". When doing this we get iceConnection successfully, but tracks received are disabled and no data is sent through them (even when the remote MediaStream received has the same id as the initial successful session remote MediaStream). Debugging and looking at the objects get really tricky because firefox webrtc inspection tool won't show every object's content as Chrome does, so it's difficult to compare initial connection objects versus the reconnection process ones later.
We also tried to listen to the onRenegotiationNeeded event but it never gets fired.

How we send sdpOffers:
```
const sendSdpOffer(): Promise<void> => {
    if (this.reconnectingAttempts >= SDP_OFFER_MAX_REPEAT_ATTEMPTS) {
      this.status = TIMED_OUT;
    }
    if (![CONNECTING].includes(this.status)) {
      return this.peerConnection.setLocalDescription()
      .finally(() =>
        this.peerConnection.createOffer({
          offerToReceiveAudio: true,
          offerToReceiveVideo: true
        })
        .finally(() => {
          this.reconnectingAttempts++;
          this.signalingClient.sendSdpOffer(this.peerConnection.localDescription);
          return;
        }));
    }
    return Promise.resolve();
  }
```

How we detect disconnection and start sending sdpOffers:
```
this.peerConnection.oniceconnectionstatechange = () => {
      const iceConnectionState = this.peerConnection.iceConnectionState;
      if (iceConnectionState === 'disconnected') {
        this.status = DISCONNECTED;
        this.sendSdpOffer()
        .then(() => {
          this.sdpOfferInterval = setInterval(this.sendSdpOffer, SDP_OFFER_REPEAT_INTERVAL);
        });
      } else if (iceConnectionState === 'failed') {
        this.status = FAILED;
      }
    };
```
Then on sdpAnswer we stop sending further offers and continue the same process as the first connection.:

```
onSdpAnswer = (answer) => {
    clearInterval(this.sdpOfferInterval);
    this.reconnectingAttempts = 0;
    this.status = CONNECTING;
    this.peerConnection.setRemoteDescription(answer).catch((err) => this.logService.error);
  };
```

**Comment by Sean-Der** [comment] 2020-06-17 23:06
Hey @ulayera 

So just to confirm this doesn't have anything to do with mesh? It sounds like re-negotation between FireFox/Chromium is failing?

When doing an iceRestart are you doing it on both sides? What browser is offering/answering? I will work on reproducing and getting you some answers.

thanks

**Comment by ulayera** [comment] 2020-06-18 20:15
It doesn't seem to be the mesh. Yes the renegotiation is failing.

I do iceRestart only on offer from Viewer, assuming the Master, upon receiving the offer without icecandidates, will attempt to create new ones.

**Comment by lherman-cs** [comment] 2020-07-06 16:51
Due to staleness and the question is related to browser APIs. I'll close this issue. Please feel free to reopen if you need further assistance.

**Closed by lherman-cs** 2020-07-06 16:51 UTC
