### ISSUE TITLE
40s latency for gathering ICE candidates

### ISSUE THREAD

**Issue by sharadrj** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#53] opened 2020-05-22 16:23 UTC
Got report below that it can take ~40s latency for gathering ICE candidates - 

Tried three different options for JS webpage Master (using the same channel that works fine with the C SDK master) –
 
JS Webpage as Master with STUN/TURN – takes ~40s (logs)
JS Webpage as Master with TURN only – takes ~40s (logs)
JS Webpage as Master with DISABLED option – takes ~200ms for host candidates only, but mostly fails to stream (logs)

**Comment by lherman-cs** [comment] 2020-05-26 14:31
@sharadrj Do you mind to share the logs too?

**Comment by modescode** [comment] 2020-05-26 20:00
@lherman-cs here you are the logs for above scenarios (can share un-redacted logs offline)-

Here are the logs - 
**1. JS Webpage as Master with STUN/TURN - takes ~40s** 
`[2020-05-22T15:29:03.739Z] [INFO] Page loaded
[2020-05-22T15:29:07.116Z] [INFO] [MASTER] Channel ARN:  arn:aws:kinesisvideo:us-east-1:86xxxxxx9137:channel/rmodexxxxxxxxchannel/158xxxxxx6579
[INFO] [MASTER] Endpoints:  {
  "WSS": "wss://m-a1e2xxxx.kinesisvideo.us-east-1.amazonaws.com",
  "HTTPS": "https://r-0606xxxx.kinesisvideo.us-east-1.amazonaws.com"
}
[2020-05-22T15:29:07.826Z] [INFO] [MASTER] ICE servers:  [
  {
    "urls": "stun:stun.kinesisvideo.us-east-1.amazonaws.com:443"
  },
  {
    "urls": [
      "turn:54-xxx-188-115.t-774ccc2f.kinesisvideo.us-east-1.amazonaws.com:443"
    ],
    "username": "15xxxxxx47:djE6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxRrdnNjaGFubmVsLzE1ODc2MTIyMzY1Nzk=",
    "credential": "Qq8+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx+1Zo4sej0B2/BOikk="
  },
  {
    "urls": [
      "turn:34-234-94-239.t-774ccc2f.kinesisvideo.us-east-1.amazonaws.com:443"
    ],
    "username": "15xxxxxx47:djE6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxRrdnNjaGFubmVsLzE1ODc2MTIyMzY1Nzk=",
    "credential": "Qq8+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx+1Zo4sej0B2/BOikk="
  }
]
[2020-05-22T15:29:08.867Z] [INFO] [MASTER] Starting master connection
[2020-05-22T15:29:09.463Z] [INFO] [MASTER] Connected to signaling service
[2020-05-22T15:29:48.756Z] [INFO] [MASTER] Received SDP offer from client: echoShow622
[2020-05-22T15:29:48.822Z] [INFO] [MASTER] Received remote track from client: echoShow622
[2020-05-22T15:29:48.823Z] [INFO] [MASTER] Received remote track from client: echoShow622
[2020-05-22T15:29:48.827Z] [INFO] [MASTER] Creating SDP answer for client: echoShow622
[2020-05-22T15:29:48.852Z] [INFO] [MASTER] Generating ICE candidates for client: echoShow622
[2020-05-22T15:29:48.853Z] [INFO] [MASTER] Generated ICE candidate for client: echoShow622
[2020-05-22T15:29:48.953Z] [INFO] [MASTER] Generated ICE candidate for client: echoShow622
[2020-05-22T15:29:49.018Z] [INFO] [MASTER] Generated ICE candidate for client: echoShow622
[2020-05-22T15:29:49.139Z] [INFO] [MASTER] Generated ICE candidate for client: echoShow622
[2020-05-22T15:29:49.141Z] [INFO] [MASTER] Generated ICE candidate for client: echoShow622
[2020-05-22T15:30:28.705Z] [INFO] [MASTER] All ICE candidates have been generated for client: echoShow622
[2020-05-22T15:30:28.705Z] [INFO] [MASTER] Sending SDP answer to client: echoShow622`




**2. JS Webpage as Master with TURN only – takes ~40s (logs)**
`[2020-05-22T15:33:47.516Z] [INFO] Page loaded
[2020-05-22T15:33:50.670Z] [INFO] [MASTER] Channel ARN:  arn:aws:kinesisvideo:us-east-1:86xxxxxx9137:channel/rmodexxxxxxxxchannel/158xxxxxx6579
[INFO] [MASTER] Endpoints:  {
  "WSS": "wss://m-a1e2xxxx.kinesisvideo.us-east-1.amazonaws.com",
  "HTTPS": "https://r-0606xxxx.kinesisvideo.us-east-1.amazonaws.com"
}
[2020-05-22T15:33:51.468Z] [INFO] [MASTER] ICE servers:  [
  {
    "urls": [
      "turn:54-xxx136-248.t-774ccc2f.kinesisvideo.us-east-1.amazonaws.com:443"
    ],
   "username": "15xxxxxx47:djE6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxRrdnNjaGFubmVsLzE1ODc2MTIyMzY1Nzk=",
    "credential": "Qq8+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx+1Zo4sej0B2/BOikk="
  }
]
[2020-05-22T15:33:52.193Z] [INFO] [MASTER] Starting master connection
[2020-05-22T15:33:52.826Z] [INFO] [MASTER] Connected to signaling service
[2020-05-22T15:34:03.965Z] [INFO] [MASTER] Received SDP offer from client: echoShow848
[2020-05-22T15:34:03.988Z] [INFO] [MASTER] Received remote track from client: echoShow848
[2020-05-22T15:34:03.988Z] [INFO] [MASTER] Received remote track from client: echoShow848
[2020-05-22T15:34:04.003Z] [INFO] [MASTER] Creating SDP answer for client: echoShow848
[2020-05-22T15:34:04.028Z] [INFO] [MASTER] Generating ICE candidates for client: echoShow848
[2020-05-22T15:34:04.302Z] [INFO] [MASTER] Generated ICE candidate for client: echoShow848
[2020-05-22T15:34:43.838Z] [INFO] [MASTER] All ICE candidates have been generated for client: echoShow848
[2020-05-22T15:34:43.838Z] [INFO] [MASTER] Sending SDP answer to client: echoShow848`


**3. JS Webpage as Master with DISABLED option – takes ~200ms for host candidates only, but mostly fails to stream (logs)**

`[2020-05-22T15:44:59.497Z] [INFO] Page loaded
[2020-05-22T15:45:02.079Z] [INFO] [MASTER] Channel ARN:  arn:aws:kinesisvideo:us-east-1:86xxxxxx9137:channel/rmodexxxxxxxxchannel/158xxxxxx6579
[2020-05-22T15:45:02.191Z] [INFO] [MASTER] Endpoints:  {
  "WSS": "wss://m-a1e2xxxx.kinesisvideo.us-east-1.amazonaws.com",
  "HTTPS": "https://r-0606xxxx.kinesisvideo.us-east-1.amazonaws.com"
}
[2020-05-22T15:45:02.518Z] [INFO] [MASTER] ICE servers:  []
[2020-05-22T15:45:03.239Z] [INFO] [MASTER] Starting master connection
[2020-05-22T15:45:03.813Z] [INFO] [MASTER] Connected to signaling service
[2020-05-22T15:45:34.355Z] [INFO] [MASTER] Received SDP offer from client: echoShow198
[2020-05-22T15:45:34.383Z] [INFO] [MASTER] Received remote track from client: echoShow198
[2020-05-22T15:45:34.386Z] [INFO] [MASTER] Received remote track from client: echoShow198
[2020-05-22T15:45:34.394Z] [INFO] [MASTER] Creating SDP answer for client: echoShow198
[2020-05-22T15:45:34.456Z] [INFO] [MASTER] Generating ICE candidates for client: echoShow198
[2020-05-22T15:45:34.459Z] [INFO] [MASTER] Generated ICE candidate for client: echoShow198
[2020-05-22T15:45:34.558Z] [INFO] [MASTER] Generated ICE candidate for client: echoShow198
[2020-05-22T15:45:34.559Z] [INFO] [MASTER] All ICE candidates have been generated for client: echoShow198
[2020-05-22T15:45:34.562Z] [INFO] [MASTER] Sending SDP answer to client: echoShow198`

**Comment by lherman-cs** [comment] 2020-05-26 20:17
@modescode it looks like the delay is coming from getting reflexive candidates from STUN. From the logs, I see that trickle ice is disabled. Could you please try to turn on the trickle ice as it will reduce the delay?

Also, to isolate the issue and make sure that this not due to the network environment, could you also test how fast your device can gather ice candidates using this test page, https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/?

**Comment by modescode** [comment] 2020-05-26 21:01
@lherman-cs - actually my tests are with Alexa Skill (using AWS JS SDK), which does not support Trickle ICE. 

That said, w/o trickle ICE, and using C SDK master, I'm able to see ~1000ms response time with all candidates gathered, running C SDK master on my mac.

**Comment by lherman-cs** [comment] 2020-05-26 21:41
@modescode I'm not sure if this is related. But, I think it has something to do with your device is IPv6 enabled, but our stun server is not. So, what happened was your WebRTC client kept sending requests to the STUN server to get the reflexive IPv6 addresses until it hit a timeout.

Regarding C SDK, which commit hash are you currently on? Because we just recently added IPv6 support. So, before having IPv6 support, the response time should be quick.

**Comment by lherman-cs** [comment] 2020-05-28 15:20
I found that 40s latency doesn't occur on Firefox, it only appears on Chrome. After some digging, I found that the main difference between the two browsers is that Chrome sent a STUN binding request even to TURN servers. 

Then, I tried to send a binding request to the TURN server, and I found that the TURN server never responded back (I need to double check this with our backend people).

So, if this is true, the root cause is that Chrome will send a STUN binding request to our TURN server, and it'll be waiting to get the response until it hits a timeout (which seems to be around 40s).

**Comment by cesarpachon** [comment] 2020-08-04 19:19
helllo I am interested in this issue.. it there is some recommendation for this issue, assuming it is a chrome problem, as the last comment suggest?

**Comment by ycyang1229** [comment] 2020-09-17 14:40
I am also interested in this issue since I have this issue too. Just take a seat here.

**Comment by MushMal** [comment] 2020-12-09 21:12
@lherman-cs do you have any updates on this?

**Comment by MushMal** [comment] 2021-01-27 19:43
Can I get some clarification whether this is reproducible with Trickle ICE disabled? If so, this is expected.

**Comment by MushMal** [comment] 2021-02-01 06:08
Resolving this issue. It is indeed possible to get multi second delays in non-trickle ice case where the local candidates take a lot of time to resolve

**Closed by MushMal** 2021-02-01 06:08 UTC
Labels: Awaiting response

**Comment by sundar505** [comment] 2023-11-03 12:15
Can we just force turn servers.

**Comment by sirknightj** [comment] 2023-11-03 16:16
@sundar505 the option is implemented here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/pull/273.

Have the peers exchange only `relay` type candidates and TURN will be used.
